version: "3"
services:
  redis:
    image: "redis/redis-stack:6.2.6-v7"
    restart: always
    ports:
      - ${REDIS_PORT:-6379}:6379
      - ${REDIS_INSIGHT_PORT:-8001}:8001
    volumes:
      - redis-data:/data

  worker:
    build:
      context: ./
      dockerfile: default.Dockerfile
    command: poetry run arq mihama.arq.worker.ArqWorkerSettings
    environment:
      - TESTING=${TESTING:-False}
      - DEBUG=${DEBUG:-False}
      - REDIS_OM_URL=redis://redis:${REDIS_PORT:-6379}
      - ARQ_REDIS_URL=redis://redis:${REDIS_PORT:-6379}
    restart: always
    depends_on:
      - redis

  api:
    build:
      context: ./
      dockerfile: default.Dockerfile
    command: poetry run gunicorn -k uvicorn.workers.UvicornWorker mihama.main:app
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    environment:
      - TESTING=${TESTING:-False}
      - DEBUG=${DEBUG:-False}
      - PORT=${PORT:-8000}
      - REDIS_OM_URL=redis://redis:${REDIS_PORT:-6379}
      - REDIS_ARQ_URL=redis://redis:${REDIS_PORT:-6379}
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
