[tool.poetry]
name = "mihama"
version = "0.6.3"
description = "osv.dev API clone for on-premise usage"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
aiometer = "^0.4.0"
arq = "^0.25.0"
decorator = "^5.1.1"
fastapi = "0.95.2"
gunicorn = "^20.1.0"
loguru = "^0.7.0"
orjson = "^3.8.14"
packageurl-python = "^0.11.1"
purl = "^1.6"
pyhumps = "^3.8.0"
redis = "^4.5.5"
redis-om = "0.1.2"
requests = "2.31.0"
returns = "^0.20.0"
semver = "^3.0.0"
typer = "^0.9.0"
ujson = "^5.7.0"
uvicorn = {extras = ["standard"], version = "^0.22"}

[tool.poetry.group.dev.dependencies]
autoflake = "^2.1"
autopep8 = "^2.0"
black = "^23.3"
flake8 = "^6.0"
httpx = "^0.24"
isort = "^5.12"
mypy = "^1.3"
nest-asyncio = "^1.5.6"
pre-commit = "^3.3"
pytest = "^7.3"
pytest-asyncio = "^0.21"
pytest-cov = "^4.1"
pytest-mock = "^3.10.0"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.7"
pyupgrade = "^3.4"
ruff = "^0.0.270"
types-requests = "2.31.0"
vcrpy = "^4.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.poetry.scripts]
mihama = "mihama.cli:app"

[tool.mypy]
plugins = ["pydantic.mypy", "returns.contrib.mypy.returns_plugin"]
ignore_missing_imports = true

[tool.ruff]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "C",    # flake8-comprehensions
    "B",    # flake8-bugbear
    "T20",  # flake8-print
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function call `...` in argument defaults
]
