[tool.poetry]
name = "mihama"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
aiocache = "0.11.1"
aiometer = "^0.3.0"
arq = "^0.24.0"
fastapi = "^0.82.0"
fastapi-cache2 = {extras = ["redis"], version = "^0.1.9"}
gunicorn = "^20.1.0"
httpx = "^0.23.0"
loguru = "^0.6.0"
osv = "^0.0.14"
purl = "^1.6"
pyhumps = "^3.7.3"
redis-om = "0.0.27"
semver = "^2.13.0"
typer = "^0.6.1"
ujson = "^5.4.0"
uvicorn = {extras = ["standard"], version = "^0.18.3"}
packageurl-python = "^0.10.1"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
autoflake = "^1.5"
autopep8 = "^1.7.0"
black = "^22.8.0"
coveralls = "^3.3.1"
isort = "^5.10.1"
mypy = "^0.971"
pre-commit = "^2.20.0"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
pytest-mock = "^3.8.2"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.5"
pyupgrade = "^2.37.3"
vcrpy = "^4.2.1"
pytest-asyncio = "^0.19.0"
nest-asyncio = "^1.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
