[tool.poetry]
name = "mihama"
version = "0.6.2"
description = "osv.dev API clone for on-premise usage"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
aiocache = "^0.12.1"
aiometer = "^0.4.0"
arq = "^0.25.0"
decorator = "^5.1.1"
fastapi = "0.95.1"
gunicorn = "^20.1.0"
loguru = "^0.7.0"
orjson = "^3.8.11"
packageurl-python = "^0.11.1"
purl = "^1.6"
pyhumps = "^3.8.0"
redis = "^4.5.4"
redis-om = "0.1.2"
requests = "^2.30.0"
returns = "^0.20.0"
semver = "^3.0.0"
typer = "^0.9.0"
ujson = "^5.7.0"
uvicorn = {extras = ["standard"], version = "^0.22"}

[tool.poetry.group.dev.dependencies]
autoflake = "^2.1"
autopep8 = "^2.0"
black = "^23.3"
flake8 = "^6.0"
httpx = "^0.24.0"
isort = "^5.12"
mypy = "^1.2"
nest-asyncio = "^1.5.6"
pre-commit = "^3.3"
pytest = "^7.3"
pytest-asyncio = "^0.21"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
pytest-randomly = "^3.12.0"
pytest-sugar = "^0.9.7"
pyupgrade = "^3.3.2"
types-requests = "^2.29"
vcrpy = "^4.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.poetry.scripts]
mihama = "mihama.cli:app"

[tool.mypy]
plugins = ["pydantic.mypy", "returns.contrib.mypy.returns_plugin"]
