version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ES_PASSWORD:-changeme}
      - xpack.security.enabled=true
    ports:
      - ${ES_PORT:-9200}:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9200/_cluster/health | grep -vq ''"status":"red"''',
        ]
      retries: 10
      interval: 20s
