name: Python CI

on: ["pull_request", "push"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      es:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        env:
          bootstrap.memory_lock: true
          discovery.type: single-node
          xpack.security.enabled: true
          ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
          ELASTIC_PASSWORD": changeme
        options: >-
          --health-cmd "curl -u elastic:changeme localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 9200:9200
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.8.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Poetry install
        run: poetry install
      - name: Run tests
        env:
          ES_HOSTS: http://locahost:9200
          ES_PASSWORD: changeme
        run: poetry run pytest
